[package]
name = "lru"
version = "0.1.13"
authors = ["Jerome Froelich <jeromefroelic@hotmail.com>"]
description = "A LRU cache implementation"
homepage = "https://github.com/jeromefroe/lru-rs"
repository = "https://github.com/jeromefroe/lru-rs.git"
documentation = "https://docs.rs/lru/"
readme = "README.md"
license = "MIT"
keywords = ["LRU", "cache"]

[features]
nightly = []

[dev-dependencies]
scoped_threadpool = "0.1.*"
hashbrown = "0.1.*"
